services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      AUTH_TOKEN_TTL: ${AUTH_TOKEN_TTL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: mirror.gcr.io/library/postgres:17
    restart: always
    container_name: tundra_market_db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=$${POSTGRES_USER} PGDATABASE=$${POSTGRES_DB} pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
