// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcdb

import (
	"context"
)

const getAdminByLogin = `-- name: GetAdminByLogin :one

SELECT id, login, password, created_at FROM admin WHERE login = $1
`

// internal/infrastructure/postgres/queries/admin.sql
func (q *Queries) GetAdminByLogin(ctx context.Context, login string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByLogin, login)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin SET password = $2 WHERE login = $1
`

type UpdateAdminPasswordParams struct {
	Login    string
	Password string
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.Login, arg.Password)
	return err
}
