// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcdb

import (
	"context"
)

const getAdminByLogin = `-- name: GetAdminByLogin :one

SELECT id, login, password_hash, created_at FROM admin WHERE login = $1
`

// internal/infrastructure/postgres/queries/admin.sql
func (q *Queries) GetAdminByLogin(ctx context.Context, login string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByLogin, login)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateAdminPasswordHash = `-- name: UpdateAdminPasswordHash :exec
UPDATE admin SET password_hash = $2 WHERE login = $1
`

type UpdateAdminPasswordHashParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) UpdateAdminPasswordHash(ctx context.Context, arg UpdateAdminPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAdminPasswordHash, arg.Login, arg.PasswordHash)
	return err
}
