// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Status string

const (
	StatusCREATED    Status = "CREATED"
	StatusPROCESSING Status = "PROCESSING"
	StatusSENT       Status = "SENT"
	StatusCOMPLETED  Status = "COMPLETED"
	StatusCANCELLED  Status = "CANCELLED"
	StatusDENIED     Status = "DENIED"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Admin struct {
	ID           int32
	Login        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

type Nomad struct {
	ID        int32
	Phone     string
	Longitude pgtype.Numeric
	Latitude  pgtype.Numeric
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Order struct {
	ID               int32
	NomadID          pgtype.Int4
	TradingStationID pgtype.Int4
	Status           Status
	Longitude        pgtype.Numeric
	Latitude         pgtype.Numeric
	Comment          pgtype.Text
	CreatedAt        pgtype.Timestamp
}

type OrdersToProduct struct {
	ID        int32
	OrdersID  int32
	ProductID int32
	Quantity  int32
	CreatedAt pgtype.Timestamp
}

type Product struct {
	ID        int32
	Name      string
	Price     pgtype.Int4
	Weight    pgtype.Int4
	Volume    pgtype.Int4
	CreatedAt pgtype.Timestamp
	Details   pgtype.Text
}

type StatusHistory struct {
	ID        int32
	OrdersID  int32
	Status    NullStatus
	CreatedAt pgtype.Timestamp
	Comment   pgtype.Text
}

type TradingStation struct {
	ID        int32
	Phone     pgtype.Text
	Name      pgtype.Text
	Longitude pgtype.Numeric
	Latitude  pgtype.Numeric
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
