// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nomad.sql

package sqlcdb

import (
	"context"
)

const createNomad = `-- name: CreateNomad :one
INSERT INTO nomad (phone)
VALUES ($1)
RETURNING id, phone, longitude, latitude, created_at, updated_at
`

func (q *Queries) CreateNomad(ctx context.Context, phone string) (Nomad, error) {
	row := q.db.QueryRow(ctx, createNomad, phone)
	var i Nomad
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNomadByID = `-- name: GetNomadByID :one
SELECT id, phone, longitude, latitude, created_at, updated_at FROM nomad WHERE id = $1
`

func (q *Queries) GetNomadByID(ctx context.Context, id int32) (Nomad, error) {
	row := q.db.QueryRow(ctx, getNomadByID, id)
	var i Nomad
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNomadByPhone = `-- name: GetNomadByPhone :one
SELECT id, phone, longitude, latitude, created_at, updated_at FROM nomad WHERE phone = $1
`

func (q *Queries) GetNomadByPhone(ctx context.Context, phone string) (Nomad, error) {
	row := q.db.QueryRow(ctx, getNomadByPhone, phone)
	var i Nomad
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
