// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (nomad_id, trading_station_id, longitude, latitude, comment)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at
`

type CreateOrderParams struct {
	NomadID          pgtype.Int4
	TradingStationID pgtype.Int4
	Longitude        pgtype.Numeric
	Latitude         pgtype.Numeric
	Comment          pgtype.Text
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.NomadID,
		arg.TradingStationID,
		arg.Longitude,
		arg.Latitude,
		arg.Comment,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.NomadID,
		&i.TradingStationID,
		&i.Status,
		&i.Longitude,
		&i.Latitude,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentOrderByNomadID = `-- name: GetCurrentOrderByNomadID :one
SELECT id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at FROM orders
WHERE nomad_id = $1
  AND status NOT IN ('CANCELLED')
ORDER BY created_at DESC
    LIMIT 1
`

func (q *Queries) GetCurrentOrderByNomadID(ctx context.Context, nomadID pgtype.Int4) (Order, error) {
	row := q.db.QueryRow(ctx, getCurrentOrderByNomadID, nomadID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.NomadID,
		&i.TradingStationID,
		&i.Status,
		&i.Longitude,
		&i.Latitude,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.NomadID,
		&i.TradingStationID,
		&i.Status,
		&i.Longitude,
		&i.Latitude,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getOrdersByNomadIDAndCategory = `-- name: GetOrdersByNomadIDAndCategory :many
SELECT id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at FROM orders
WHERE nomad_id = $1
  AND CASE $3::text
    WHEN 'NEW'        THEN status = 'CREATED'
    WHEN 'PROCESSING' THEN status IN ('PROCESSING', 'SENT')
    WHEN 'HISTORY'    THEN status IN ('COMPLETED', 'CANCELLED', 'DENIED')
END
ORDER BY created_at DESC
LIMIT  $2
OFFSET COALESCE($4::int, 0)
`

type GetOrdersByNomadIDAndCategoryParams struct {
	NomadID       pgtype.Int4
	Limit         int32
	OrderCategory string
	Anchor        int32
}

func (q *Queries) GetOrdersByNomadIDAndCategory(ctx context.Context, arg GetOrdersByNomadIDAndCategoryParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByNomadIDAndCategory,
		arg.NomadID,
		arg.Limit,
		arg.OrderCategory,
		arg.Anchor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.NomadID,
			&i.TradingStationID,
			&i.Status,
			&i.Longitude,
			&i.Latitude,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByStationAndCategory = `-- name: GetOrdersByStationAndCategory :many
SELECT id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at FROM orders
WHERE trading_station_id = $1
  AND CASE $3::text
    WHEN 'NEW'        THEN status = 'CREATED'
    WHEN 'PROCESSING' THEN status IN ('PROCESSING', 'SENT')
    WHEN 'HISTORY'    THEN status IN ('COMPLETED', 'CANCELLED', 'DENIED')
END
ORDER BY created_at DESC
LIMIT  $2
OFFSET COALESCE($4::int, 0)
`

type GetOrdersByStationAndCategoryParams struct {
	TradingStationID pgtype.Int4
	Limit            int32
	OrderCategory    string
	Anchor           int32
}

func (q *Queries) GetOrdersByStationAndCategory(ctx context.Context, arg GetOrdersByStationAndCategoryParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByStationAndCategory,
		arg.TradingStationID,
		arg.Limit,
		arg.OrderCategory,
		arg.Anchor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.NomadID,
			&i.TradingStationID,
			&i.Status,
			&i.Longitude,
			&i.Latitude,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByNomadIDUpdatedAfter = `-- name: GetOrdersByNomadIDUpdatedAfter :many
SELECT DISTINCT o.id, o.nomad_id, o.trading_station_id, o.status, o.longitude, o.latitude, o.comment, o.created_at FROM orders o
LEFT JOIN status_history sh ON sh.orders_id = o.id
WHERE o.nomad_id = $1
  AND (o.created_at > to_timestamp($2) OR sh.created_at > to_timestamp($2))
ORDER BY o.created_at DESC
`

type GetOrdersByNomadIDUpdatedAfterParams struct {
	NomadID     pgtype.Int4
	ToTimestamp float64
}

func (q *Queries) GetOrdersByNomadIDUpdatedAfter(ctx context.Context, arg GetOrdersByNomadIDUpdatedAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByNomadIDUpdatedAfter, arg.NomadID, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.NomadID,
			&i.TradingStationID,
			&i.Status,
			&i.Longitude,
			&i.Latitude,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByStationUpdatedAfter = `-- name: GetOrdersByStationUpdatedAfter :many
SELECT DISTINCT o.id, o.nomad_id, o.trading_station_id, o.status, o.longitude, o.latitude, o.comment, o.created_at FROM orders o
LEFT JOIN status_history sh ON sh.orders_id = o.id
WHERE o.trading_station_id = $1
  AND (o.created_at > to_timestamp($2) OR sh.created_at > to_timestamp($2))
ORDER BY o.created_at DESC
`

type GetOrdersByStationUpdatedAfterParams struct {
	TradingStationID pgtype.Int4
	ToTimestamp      float64
}

func (q *Queries) GetOrdersByStationUpdatedAfter(ctx context.Context, arg GetOrdersByStationUpdatedAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByStationUpdatedAfter, arg.TradingStationID, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.NomadID,
			&i.TradingStationID,
			&i.Status,
			&i.Longitude,
			&i.Latitude,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    comment = COALESCE($3, comment)
WHERE id = $1
    RETURNING id, nomad_id, trading_station_id, status, longitude, latitude, comment, created_at
`

type UpdateOrderStatusParams struct {
	ID      int32
	Status  Status
	Comment pgtype.Text
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.Comment)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.NomadID,
		&i.TradingStationID,
		&i.Status,
		&i.Longitude,
		&i.Latitude,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
