// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders_to_product.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductToOrder = `-- name: AddProductToOrder :exec
INSERT INTO orders_to_product (orders_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type AddProductToOrderParams struct {
	OrdersID  int32
	ProductID int32
	Quantity  int32
}

func (q *Queries) AddProductToOrder(ctx context.Context, arg AddProductToOrderParams) error {
	_, err := q.db.Exec(ctx, addProductToOrder, arg.OrdersID, arg.ProductID, arg.Quantity)
	return err
}

const getProductsByOrderID = `-- name: GetProductsByOrderID :many
SELECT p.id, p.name, p.weight, p.volume, otp.quantity
FROM orders_to_product otp
         JOIN product p ON p.id = otp.product_id
WHERE otp.orders_id = $1
`

type GetProductsByOrderIDRow struct {
	ID       int32
	Name     string
	Weight   pgtype.Int4
	Volume   pgtype.Int4
	Quantity int32
}

func (q *Queries) GetProductsByOrderID(ctx context.Context, ordersID int32) ([]GetProductsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByOrderID, ordersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByOrderIDRow
	for rows.Next() {
		var i GetProductsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Weight,
			&i.Volume,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
