// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_history.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStatusHistory = `-- name: AddStatusHistory :exec
INSERT INTO status_history (orders_id, status, comment)
VALUES ($1, $2, $3)
`

type AddStatusHistoryParams struct {
	OrdersID int32
	Status   NullStatus
	Comment  pgtype.Text
}

func (q *Queries) AddStatusHistory(ctx context.Context, arg AddStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, addStatusHistory, arg.OrdersID, arg.Status, arg.Comment)
	return err
}

const getStatusHistoryAfter = `-- name: GetStatusHistoryAfter :many
SELECT id, orders_id, status, comment, created_at FROM status_history
WHERE orders_id = $1
  AND created_at > to_timestamp($2)
ORDER BY created_at ASC
`

type GetStatusHistoryAfterParams struct {
	OrdersID    int32
	ToTimestamp float64
}

func (q *Queries) GetStatusHistoryAfter(ctx context.Context, arg GetStatusHistoryAfterParams) ([]StatusHistory, error) {
	rows, err := q.db.Query(ctx, getStatusHistoryAfter, arg.OrdersID, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusHistory
	for rows.Next() {
		var i StatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrdersID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusHistoryByOrderID = `-- name: GetStatusHistoryByOrderID :many
SELECT id, orders_id, status, comment, created_at FROM status_history
WHERE orders_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetStatusHistoryByOrderID(ctx context.Context, ordersID int32) ([]StatusHistory, error) {
	rows, err := q.db.Query(ctx, getStatusHistoryByOrderID, ordersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusHistory
	for rows.Next() {
		var i StatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrdersID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
