// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trading_station.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllTradingStations = `-- name: GetAllTradingStations :many
SELECT id, phone, name, longitude, latitude, created_at, updated_at FROM trading_station ORDER BY id
`

func (q *Queries) GetAllTradingStations(ctx context.Context) ([]TradingStation, error) {
	rows, err := q.db.Query(ctx, getAllTradingStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradingStation
	for rows.Next() {
		var i TradingStation
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Name,
			&i.Longitude,
			&i.Latitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradingStationByID = `-- name: GetTradingStationByID :one
SELECT id, phone, name, longitude, latitude, created_at, updated_at FROM trading_station WHERE id = $1
`

func (q *Queries) GetTradingStationByID(ctx context.Context, id int32) (TradingStation, error) {
	row := q.db.QueryRow(ctx, getTradingStationByID, id)
	var i TradingStation
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTradingStationByPhone = `-- name: GetTradingStationByPhone :one
SELECT id, phone, name, longitude, latitude, created_at, updated_at FROM trading_station WHERE phone = $1
`

func (q *Queries) GetTradingStationByPhone(ctx context.Context, phone pgtype.Text) (TradingStation, error) {
	row := q.db.QueryRow(ctx, getTradingStationByPhone, phone)
	var i TradingStation
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTradingStationPhone = `-- name: SetTradingStationPhone :one
UPDATE trading_station
SET phone = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, name, longitude, latitude, created_at, updated_at
`

type SetTradingStationPhoneParams struct {
	ID    int32
	Phone pgtype.Text
}

func (q *Queries) SetTradingStationPhone(ctx context.Context, arg SetTradingStationPhoneParams) (TradingStation, error) {
	row := q.db.QueryRow(ctx, setTradingStationPhone, arg.ID, arg.Phone)
	var i TradingStation
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
